/**
 * The same schema, in PostgreSQL.
 *
 * Step one of moving off SQLite. The database is embedded today, which is fine
 * on one machine and fatal in a container: `/app/data` is replaced with the
 * task, and the accounts go with it. So the platform has to be able to speak to
 * a managed Postgres — RDS, now that the deployment target is AWS.
 *
 * ## Translated, not copied
 *
 * The Postgres DDL is produced from `SCHEMA_SQL` in `server/db.js` at run time
 * rather than kept as a second file. A schema maintained in two places is a
 * schema that disagrees with itself within a month — somebody adds a column to
 * the one they are looking at, the other keeps working locally, and the
 * difference is discovered by a production insert. Here, adding a table to
 * `server/db.js` puts it in Postgres too, or `scripts/test-pg-schema.mjs` goes
 * red against a real server.
 *
 * ## What actually differs
 *
 * Remarkably little, because the schema was written plainly: no `WITHOUT
 * ROWID`, no `COLLATE`, no SQLite date functions, and only three column types
 * in the whole thing.
 *
 *   · `INTEGER PRIMARY KEY AUTOINCREMENT` is SQLite's rowid alias. Postgres
 *     wants an identity column. `BY DEFAULT` rather than `ALWAYS`, so a row
 *     inserted with an explicit id — which the seed does — still works.
 *   · `REAL` is a 64-bit float in SQLite and a 32-bit one in Postgres. It holds
 *     marks and ease factors here, so it becomes `DOUBLE PRECISION`; taking the
 *     name at face value would quietly halve the precision of every score.
 *   · Nothing else. `TEXT`, `INTEGER`, `NOT NULL`, `DEFAULT`, `REFERENCES …
 *     ON DELETE CASCADE`, `UNIQUE(…)`, partial-free indexes and `DESC` in an
 *     index all mean the same thing in both.
 *
 * Deliberately NOT changed: dates stay `TEXT` holding ISO-8601, and booleans
 * stay `INTEGER` holding 0 or 1. Both are tempting to "fix" to `timestamptz`
 * and `boolean`, and both would change what comparisons mean in a few hundred
 * queries that already work — `expires_at <= ?` against a string is a different
 * animal from the same test against a timestamp. That is a separate, later
 * decision, and it is not this one.
 */
'use strict';

/** SQLite's rowid alias → a Postgres identity column. */
const AUTOINCREMENT = /\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi;

/* Word-boundary REAL only: it must not touch a column NAMED something-real.
   The `|$` in the lookahead is not decoration. This function is also handed a
   bare type on its own — `addColumnIfMissing('attempt_answers','earned','REAL')`
   passes exactly the four characters — and without it the pattern needs a
   trailing delimiter that a lone type has not got. Two mark columns went across
   as 32-bit floats before a real server was asked what it had built. */
const REAL_TYPE = /(^|[\s(,])REAL(?=[\s,)]|$)/gi;

/**
 * Translate the project's SQLite DDL into PostgreSQL.
 * @param {string} sqliteDdl the text of SCHEMA_SQL
 * @returns {string} DDL that Postgres accepts
 */
function toPostgres(sqliteDdl) {
  return String(sqliteDdl)
    .replace(AUTOINCREMENT, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(REAL_TYPE, '$1DOUBLE PRECISION');
}

/**
 * The table names the schema defines, in order.
 * Used by the test to compare the two databases rather than trusting that the
 * translation "looked right".
 */
function tableNames(ddl) {
  return [...String(ddl).matchAll(/CREATE TABLE (?:IF NOT EXISTS )?([A-Za-z_][A-Za-z0-9_]*)/gi)]
    .map(m => m[1]);
}

/** The index names, likewise. */
function indexNames(ddl) {
  return [...String(ddl).matchAll(/CREATE (?:UNIQUE )?INDEX (?:IF NOT EXISTS )?([A-Za-z_][A-Za-z0-9_]*)/gi)]
    .map(m => m[1]);
}

/**
 * The late columns and indexes come from `server/db.js`, which records each one
 * as it applies it. They are NOT listed again here: a hand-kept copy of that
 * list was written while this file was, and was missing six columns before the
 * hour was out. The only list that cannot be wrong is the one the migrations
 * themselves fill in.
 *
 * `ADD COLUMN IF NOT EXISTS` is native in Postgres, so unlike SQLite this needs
 * no read of the table definition first.
 */

/**
 * The whole thing: tables, then the late columns and indexes, ready to execute.
 *
 * @param {string} sqliteDdl   SCHEMA_SQL from server/db.js
 * @param {Array}  addedColumns  its ADDED_COLUMNS
 * @param {Array}  addedIndexes  its ADDED_INDEXES
 */
function fullPostgresDdl(sqliteDdl, addedColumns, addedIndexes) {
  const parts = [toPostgres(sqliteDdl)];
  for (const [table, column, definition] of addedColumns || []) {
    /* The type goes through the same translation as the table body — one of
       these is REAL, and a mark stored as a 32-bit float is a mark that no
       longer round-trips. */
    parts.push(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${column} ${toPostgres(definition)};`);
  }
  parts.push(...(addedIndexes || []).map(x => x.replace(/;?$/, ';')));
  return parts.join('\n');
}

module.exports = { toPostgres, fullPostgresDdl, tableNames, indexNames };
