/**
 * Google Cloud Storage: the access token, and the driver that spends it.
 *
 * Run: node scripts/test-gcs.mjs   (needs no server, no browser, no database)
 *
 * Nothing here talks to Google. Two things stand in for it, and between them
 * they cover everything except Google's own machines:
 *
 *  · **A real RSA key pair**, generated by the test. The signed assertion is
 *    verified against the public half, so "we sign an RS256 JWT correctly" is
 *    checked by cryptography rather than by reading the code and agreeing with
 *    it. A wrong digest, a wrong encoding or a mangled segment all fail here.
 *  · **A fake Google over HTTP**: the token endpoint and the storage JSON API,
 *    both asserting on what arrives. That is where the request SHAPES are
 *    pinned — the method, the path, the query, the `Metadata-Flavor` header
 *    the metadata server refuses to work without, and the percent-encoded
 *    object name. Every one of those is a thing that works locally and fails in
 *    production if it is wrong, which is exactly the kind of mistake a fake is
 *    worth having.
 */
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';

const require_ = createRequire(import.meta.url);
const googleToken = require_('../server/google-token.js');
const storage = require_('../server/storage.js');

let pass = 0, fail = 0;
const ok = (c, name, detail) => {
  if (c) { pass++; console.log('✓ ' + name); return; }
  fail++;
  console.log('✗ ' + name + (detail === undefined ? '' : '  → ' + detail));
};
const head = t => console.log('\n\x1b[1m== ' + t + ' ==\x1b[0m');

/** Set some environment variables, run, put everything back. */
async function withEnv(vars, fn) {
  const before = new Map(Object.keys(vars).map(k => [k, process.env[k]]));
  for (const [k, v] of Object.entries(vars)) {
    if (v === undefined) delete process.env[k]; else process.env[k] = v;
  }
  googleToken.resetCache();
  try { return await fn(); }
  finally {
    for (const [k, v] of before) {
      if (v === undefined) delete process.env[k]; else process.env[k] = v;
    }
    googleToken.resetCache();
  }
}

/** Every credential env var off, so a stray one on the machine cannot pass a test. */
const NO_CREDENTIAL = {
  GOOGLE_SERVICE_ACCOUNT_JSON: undefined,
  GOOGLE_APPLICATION_CREDENTIALS: undefined,
  GCE_METADATA_HOST: undefined,
  K_SERVICE: undefined,
  AUDIO_STORAGE: undefined,
  GCS_BUCKET: undefined,
  STORAGE_EMULATOR_HOST: undefined,
  NODE_ENV: undefined
};
const env = extra => Object.assign({}, NO_CREDENTIAL, extra || {});

/* One key pair for the whole run: 2048 bits is a second of CPU, and every
   assertion below is verified against the public half of this. */
const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' }
});

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'gcs-test-'));
const serviceAccount = extra => JSON.stringify(Object.assign({
  type: 'service_account',
  project_id: 'vpet-prep-test',
  private_key_id: 'key-1',
  private_key: privateKey,
  client_email: 'uploader@vpet-prep-test.iam.gserviceaccount.com'
}, extra || {}));

/** Verify a JWT the way Google would, and hand back its two decoded halves. */
function openAssertion(jwt) {
  const parts = String(jwt).split('.');
  if (parts.length !== 3) return null;
  const verified = crypto.createVerify('RSA-SHA256')
    .update(`${parts[0]}.${parts[1]}`)
    .verify(publicKey, Buffer.from(parts[2], 'base64url'));
  const json = i => JSON.parse(Buffer.from(parts[i], 'base64url').toString('utf8'));
  return { verified, header: json(0), claims: json(1), parts };
}

/** A throwaway HTTP server. `handler` gets (req, res, body). */
async function serve(handler) {
  const seen = [];
  const server = http.createServer((req, res) => {
    const chunks = [];
    req.on('data', c => chunks.push(c));
    req.on('end', () => {
      const body = Buffer.concat(chunks);
      seen.push({ method: req.method, url: req.url, headers: req.headers, body });
      handler(req, res, body, seen);
    });
  });
  await new Promise(r => server.listen(0, '127.0.0.1', r));
  const { port } = server.address();
  return {
    seen,
    host: `127.0.0.1:${port}`,
    origin: `http://127.0.0.1:${port}`,
    close: () => new Promise(r => server.close(r))
  };
}

const json = (res, code, obj) => {
  res.writeHead(code, { 'content-type': 'application/json' });
  res.end(JSON.stringify(obj));
};

/* A minimal but real MP3 opening: an ID3v2 tag, which is one of the two
   things storage.js sniffs for. */
const MP3 = Buffer.concat([Buffer.from('ID3'), Buffer.alloc(200, 7)]);

try {
  /* ============ 1. Finding the credential ============ */
  head('Where the credential comes from');

  await withEnv(env(), () => {
    ok(googleToken.credentialSource() === null, 'With nothing set, there is no credential');
    ok(googleToken.configured() === false, 'and nothing claims to be configured');
    ok(googleToken.serviceAccount() === null, 'and there is no service account to read');
  });

  await withEnv(env({ GOOGLE_SERVICE_ACCOUNT_JSON: serviceAccount() }), () => {
    ok(googleToken.credentialSource() === 'service-account', 'Inline JSON is a service-account credential');
    const cred = googleToken.serviceAccount();
    ok(cred.client_email.startsWith('uploader@'), 'and it parses', cred && cred.client_email);
  });

  await withEnv(env({
    GOOGLE_SERVICE_ACCOUNT_JSON: Buffer.from(serviceAccount()).toString('base64')
  }), () => {
    /* A PEM inside an env var is a fight in most deployment UIs, so base64 is
       accepted and detected by shape rather than by a second switch. */
    const cred = googleToken.serviceAccount();
    ok(cred && cred.client_email.startsWith('uploader@'), 'The same credential base64-encoded parses identically');
  });

  {
    const file = path.join(tmp, 'key.json');
    fs.writeFileSync(file, serviceAccount());
    await withEnv(env({ GOOGLE_APPLICATION_CREDENTIALS: file }), () => {
      ok(googleToken.credentialSource() === 'service-account', 'Google\'s own env var names a key file');
      ok(googleToken.serviceAccount().private_key_id === 'key-1', 'and the file is read');
    });
  }

  await withEnv(env({ GOOGLE_APPLICATION_CREDENTIALS: path.join(tmp, 'nope.json') }), () => {
    let threw = null;
    try { googleToken.serviceAccount(); } catch (e) { threw = e; }
    ok(threw && /could not be read/.test(threw.message), 'A key file that is not there says so, and names the path',
      threw && threw.message);
  });

  const broken = [
    ['not json at all', /not valid JSON/, 'Something that is not JSON'],
    [JSON.stringify({ private_key: privateKey }), /no client_email/, 'A credential with no client_email'],
    [JSON.stringify({ client_email: 'a@b.c' }), /no private_key/, 'A credential with no private_key'],
    [JSON.stringify({ client_email: 'a@b.c', private_key: 'hunter2' }), /not a PEM/, 'A private_key that is not a PEM']
  ];
  for (const [text, pattern, label] of broken) {
    await withEnv(env({ GOOGLE_SERVICE_ACCOUNT_JSON: text }), () => {
      let threw = null;
      try { googleToken.serviceAccount(); } catch (e) { threw = e; }
      ok(threw && pattern.test(threw.message), label + ' is refused, saying which part is wrong',
        threw && threw.message);
      ok(threw && !threw.message.includes('PRIVATE KEY'), '…without printing the key in the error');
    });
  }

  await withEnv(env({ K_SERVICE: 'vpet-prep' }), () => {
    ok(googleToken.credentialSource() === 'metadata',
      'On Cloud Run, K_SERVICE means the metadata server, with no key anywhere');
  });

  /* ============ 2. The assertion, checked with real crypto ============ */
  head('The signed assertion');

  await withEnv(env({ GOOGLE_SERVICE_ACCOUNT_JSON: serviceAccount() }), () => {
    const now = Date.UTC(2026, 7, 12, 9, 0, 0);
    const jwt = googleToken.signAssertion(googleToken.serviceAccount(), 'https://example.test/scope', now);
    const open = openAssertion(jwt);

    ok(open !== null && open.verified,
      'The signature verifies against the public half of the key that signed it');
    ok(open.header.alg === 'RS256' && open.header.typ === 'JWT', 'Header says RS256',
      JSON.stringify(open.header));
    ok(open.header.kid === 'key-1', 'and carries the key id, so a rotated key can be told apart');
    ok(open.claims.iss === 'uploader@vpet-prep-test.iam.gserviceaccount.com',
      'The issuer is the service account', open.claims.iss);
    ok(open.claims.scope === 'https://example.test/scope', 'The requested scope is what is asked for');
    ok(open.claims.aud === googleToken.TOKEN_URI, 'The audience is Google\'s token endpoint', open.claims.aud);
    ok(open.claims.iat === Math.floor(now / 1000), 'iat comes from the clock it was given', String(open.claims.iat));
    ok(open.claims.exp === open.claims.iat + 3600, 'and it expires an hour later, Google\'s maximum');
    ok(open.parts.every(p => !/[+/=]/.test(p)),
      'Every segment is base64URL, not base64 — a "+" here is a signature that fails in production');

    const custom = googleToken.signAssertion(
      Object.assign(googleToken.serviceAccount(), { token_uri: 'https://elsewhere.test/token' }),
      's', now);
    ok(openAssertion(custom).claims.aud === 'https://elsewhere.test/token',
      'A credential naming its own token_uri is honoured — that field is in every real key file');
  });

  /* ============ 3. Trading it for a token ============ */
  head('The token exchange');

  {
    let grant = null, assertion = null, mints = 0;
    const google = await serve((req, res, body) => {
      mints++;
      const form = new URLSearchParams(body.toString());
      grant = form.get('grant_type');
      assertion = form.get('assertion');
      json(res, 200, { access_token: 'ya29.fake-' + mints, expires_in: 3600, token_type: 'Bearer' });
    });

    await withEnv(env({
      GOOGLE_SERVICE_ACCOUNT_JSON: serviceAccount({ token_uri: `${google.origin}/token` })
    }), async () => {
      const token = await googleToken.accessToken('scope-a');
      ok(token === 'ya29.fake-1', 'An access token comes back', token);
      ok(grant === 'urn:ietf:params:oauth:grant-type:jwt-bearer',
        'sent with the JWT bearer grant type from RFC 7523', String(grant));
      ok(google.seen[0].headers['content-type'] === 'application/x-www-form-urlencoded',
        'as a form post, which is the only encoding the endpoint accepts',
        google.seen[0].headers['content-type']);
      const open = openAssertion(assertion);
      ok(open && open.verified, 'and the assertion Google receives is the signed one');

      await googleToken.accessToken('scope-a');
      await googleToken.accessToken('scope-a');
      ok(mints === 1, 'A token that is still good is reused, not re-minted', `mints=${mints}`);

      await googleToken.accessToken('scope-b');
      ok(mints === 2, 'A different scope gets its own token', `mints=${mints}`);

      googleToken.resetCache();
      const four = await Promise.all([1, 2, 3, 4].map(() => googleToken.accessToken('scope-a')));
      ok(mints === 3, 'Four callers at once share one refresh rather than minting four', `mints=${mints}`);
      ok(new Set(four).size === 1, 'and all four get the same token');
    });
    await google.close();
  }

  {
    /* expires_in shorter than the refresh skew: the token is never considered
       fresh, which is what proves the skew is applied at all. */
    let mints = 0;
    const google = await serve((req, res) => {
      mints++;
      json(res, 200, { access_token: 'short-' + mints, expires_in: 30 });
    });
    await withEnv(env({
      GOOGLE_SERVICE_ACCOUNT_JSON: serviceAccount({ token_uri: `${google.origin}/token` })
    }), async () => {
      await googleToken.accessToken('s');
      const second = await googleToken.accessToken('s');
      ok(mints === 2 && second === 'short-2',
        'A token expiring inside the refresh window is replaced rather than used', `mints=${mints}`);
    });
    await google.close();
  }

  {
    let fails = 2;
    const google = await serve((req, res) => {
      if (fails-- > 0) return json(res, 400, { error: 'invalid_grant', error_description: 'clock skew' });
      json(res, 200, { access_token: 'recovered', expires_in: 3600 });
    });
    await withEnv(env({
      GOOGLE_SERVICE_ACCOUNT_JSON: serviceAccount({ token_uri: `${google.origin}/token` })
    }), async () => {
      let threw = null;
      try { await googleToken.accessToken('s'); } catch (e) { threw = e; }
      ok(threw && /400/.test(threw.message), 'A refused exchange throws with the status', threw && threw.message);
      ok(threw && /invalid_grant/.test(threw.message), 'and with Google\'s reason, which is the useful half');
      ok(threw && !threw.message.includes('assertion='),
        'but never with the assertion, which is a bearer credential in its own right');

      /* A failure must not leave a rejected promise in the cache for every
         later caller to await and re-throw for the life of the process. */
      let second = null;
      try { await googleToken.accessToken('s'); } catch (e) { second = e; }
      ok(second !== null, 'A second attempt fails on its own merits');
      const third = await googleToken.accessToken('s');
      ok(third === 'recovered', 'and once the cause clears, it recovers rather than staying poisoned', third);
    });
    await google.close();
  }

  /* ============ 4. The metadata server ============ */
  head('The metadata server (Cloud Run, no key at all)');

  {
    const meta = await serve((req, res) => {
      /* The real metadata server refuses without this header, precisely so a
         confused proxy cannot be tricked into fetching a token. A driver that
         forgets it works nowhere except in a test that also forgets. */
      if (req.headers['metadata-flavor'] !== 'Google') return json(res, 403, { error: 'missing flavor' });
      if (req.url !== '/computeMetadata/v1/instance/service-accounts/default/token') {
        return json(res, 404, { error: 'wrong path: ' + req.url });
      }
      json(res, 200, { access_token: 'metadata-token', expires_in: 3599, token_type: 'Bearer' });
    });

    await withEnv(env({ GCE_METADATA_HOST: meta.host }), async () => {
      ok(googleToken.credentialSource() === 'metadata', 'GCE_METADATA_HOST selects the metadata source');
      const token = await googleToken.accessToken('ignored-here');
      ok(token === 'metadata-token', 'A token comes back with no key involved', token);
      ok(meta.seen[0].headers['metadata-flavor'] === 'Google',
        'and the Metadata-Flavor header the server insists on was sent');
      ok(meta.seen[0].url.endsWith('/service-accounts/default/token'),
        'from the default service account of the instance', meta.seen[0].url);
    });
    await meta.close();
  }

  /* ============ 5. The driver, against a fake Cloud Storage ============ */
  head('The Cloud Storage driver');

  {
    const objects = new Map();
    let failNextPut = false;
    const gcs = await serve((req, res, body) => {
      if (req.url.startsWith('/token')) return json(res, 200, { access_token: 'gcs-token', expires_in: 3600 });
      if (req.headers.authorization !== 'Bearer gcs-token') return json(res, 401, { error: 'no bearer' });

      const url = new URL(req.url, 'http://x');
      if (req.method === 'POST' && url.pathname === '/upload/storage/v1/b/vpet-audio/o') {
        if (failNextPut) { failNextPut = false; return json(res, 503, { error: 'backend unavailable' }); }
        objects.set(url.searchParams.get('name'), body);
        return json(res, 200, { name: url.searchParams.get('name'), size: String(body.length) });
      }
      const m = url.pathname.match(/^\/storage\/v1\/b\/vpet-audio\/o\/(.+)$/);
      if (m) {
        const name = decodeURIComponent(m[1]);
        if (req.method === 'GET') {
          if (!objects.has(name)) return json(res, 404, { error: 'not found' });
          res.writeHead(200, { 'content-type': 'audio/mpeg' });
          return res.end(objects.get(name));
        }
        if (req.method === 'DELETE') {
          if (!objects.has(name)) return json(res, 404, { error: 'not found' });
          objects.delete(name);
          res.writeHead(204); return res.end();
        }
      }
      json(res, 404, { error: 'unexpected ' + req.method + ' ' + req.url });
    });

    await withEnv(env({
      AUDIO_STORAGE: 'gcs',
      GCS_BUCKET: 'vpet-audio',
      STORAGE_EMULATOR_HOST: gcs.origin,
      GOOGLE_SERVICE_ACCOUNT_JSON: serviceAccount({ token_uri: `${gcs.origin}/token` })
    }), async () => {
      ok(storage.driverName() === 'gcs', 'With a bucket and a credential, the driver is gcs', storage.driverName());

      const put = await storage.put(MP3, 'audio/mpeg');
      ok(put.driver === 'gcs' && put.bytes === MP3.length, 'An MP3 uploads', JSON.stringify(put));
      ok(storage.safeKey(put.key), 'and the key is generated here, never taken from the upload', put.key);

      const upload = gcs.seen.find(s => s.method === 'POST' && s.url.startsWith('/upload/'));
      ok(/[?&]uploadType=media(&|$)/.test(upload.url), 'as a media upload', upload.url);
      ok(upload.url.includes('name=' + encodeURIComponent(put.key)),
        'with the object name percent-encoded in the query — the slash included', upload.url);
      ok(upload.headers['content-type'] === 'audio/mpeg', 'and declared as audio/mpeg');
      ok(Buffer.compare(upload.body, MP3) === 0, 'The bytes that arrive are the bytes that were sent');

      const got = await storage.get(put.key);
      ok(Buffer.compare(got.body, MP3) === 0, 'and reading it back gives the same bytes');
      const read = gcs.seen.find(s => s.method === 'GET' && s.url.includes('/storage/v1/'));
      ok(read.url.includes('/o/' + encodeURIComponent(put.key)),
        'The read escapes the whole object name in the PATH, where a bare slash addresses something else',
        read.url);
      ok(read.url.endsWith('?alt=media'), 'and asks for the bytes rather than the metadata', read.url);

      await storage.remove(put.key);
      ok(!objects.has(put.key), 'Deleting really deletes');

      let threw = null;
      try { await storage.remove(put.key); } catch (e) { threw = e; }
      ok(threw === null, 'Deleting something already gone is not an error — the caller wanted it gone');

      failNextPut = true;
      let putErr = null;
      try { await storage.put(MP3, 'audio/mpeg'); } catch (e) { putErr = e; }
      ok(putErr && /503/.test(putErr.message), 'A refused upload throws with the status', putErr && putErr.message);
      ok(putErr && !putErr.message.includes('gcs-token'),
        'and never with the bearer token in the message');

      let getErr = null;
      try { await storage.get('ab/' + 'f'.repeat(32) + '.mp3'); } catch (e) { getErr = e; }
      ok(getErr && /404/.test(getErr.message), 'Reading an object that is not there says 404');

      let keyErr = null;
      try { await storage.get('../../../etc/passwd'); } catch (e) { keyErr = e; }
      ok(keyErr && keyErr.code === 'INVALID_KEY',
        'A key that could climb out of the bucket is refused before any request is made');

      /* The sniffing is the driver-independent half, but it has to still apply
         with a remote driver: this is the one place bytes come from outside. */
      let mimeErr = null;
      try { await storage.put(Buffer.from('MZ\x90\x00 this is a windows binary'), 'audio/mpeg'); }
      catch (e) { mimeErr = e; }
      ok(mimeErr && mimeErr.code === 'INVALID_AUDIO',
        'Renaming a binary to .mp3 is still refused on content, remote driver or not');
    });
    await gcs.close();
  }

  /* ============ 6. What happens without the credential ============ */
  head('Choosing a driver');

  await withEnv(env(), () => {
    ok(storage.driverName() === 'disk', 'Nothing configured means disk');
  });

  await withEnv(env({ AUDIO_STORAGE: 'gcs' }), () => {
    ok(storage.driverName() === 'disk',
      'Off Cloud Run with no key, gcs falls back to disk rather than refusing to run');
  });

  await withEnv(env({ AUDIO_STORAGE: 'gcs', GCS_BUCKET: 'b', NODE_ENV: 'production' }), () => {
    let threw = null;
    try { storage.driverName(); } catch (e) { threw = e; }
    ok(threw && /Google credential/.test(threw.message),
      'In PRODUCTION the same gap refuses to start: a silent fall back to a disk that '
      + 'evaporates on the next deploy is data loss, not degradation', threw && threw.message);
  });

  await withEnv(env({
    AUDIO_STORAGE: 'gcs', K_SERVICE: 'vpet', NODE_ENV: 'production'
  }), () => {
    let threw = null;
    try { storage.driverName(); } catch (e) { threw = e; }
    ok(threw && /GCS_BUCKET/.test(threw.message), 'and it names the missing bucket too',
      threw && threw.message);
  });

  await withEnv(env({
    AUDIO_STORAGE: 'gcs', GCS_BUCKET: 'b', K_SERVICE: 'vpet', NODE_ENV: 'production'
  }), () => {
    ok(storage.driverName() === 'gcs', 'With both, production is happy');
  });

  await withEnv(env({ AUDIO_STORAGE: 'supabase' }), () => {
    let threw = null;
    try { storage.driverName(); } catch (e) { threw = e; }
    ok(threw && /SUPABASE_URL/.test(threw.message),
      'Supabase without its keys still refuses, as it did before', threw && threw.message);
  });

  await withEnv(env({ AUDIO_STORAGE: 'GCS', GCS_BUCKET: 'b', K_SERVICE: 'v' }), () => {
    ok(storage.driverName() === 'gcs', 'The driver name is read case-insensitively');
  });
} catch (e) {
  fail++;
  console.log('\n✗ The test itself threw:\n', e);
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}

console.log(`\n${fail === 0 ? '\x1b[32m✔' : '\x1b[31m✗'} ${pass} passed, ${fail} failed\x1b[0m`);
process.exit(fail === 0 ? 0 : 1);
